In [1]:
import pandas as pd
from collections import Counter
from sklearn.naive_bayes import MultinomialNB
from sklearn import metrics
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection  import train_test_split

In [2]:
datasets=pd.read_csv("E:/Users/hashim/Documents/cse 19-23/4th yr/project/dataset/gsheets/data.csv")


In [3]:
print(sorted(Counter(datasets['LABEL']).items()))

[(0, 4846), (1, 699), (2, 495)]


In [19]:
X=datasets['TEXT']
Y1=datasets['LABEL']

In [27]:
print(X.head())

0    Your opinion about me? 1. Over 2. Jada 3. Kusr...
1    What's up? Do you want me to come online? If y...
2                         So u workin overtime nigpun?
3    Also sir, i sent you an email about how to log...
4    Please Stay At Home. To encourage the notion o...
Name: TEXT, dtype: object


In [20]:
from sklearn.feature_extraction.text import TfidfVectorizer
vect = TfidfVectorizer()

In [22]:
vect.fit(X)
#vect.vocabulary_

TfidfVectorizer()

In [23]:
vect = TfidfVectorizer(stop_words='english')
vect.fit(X)

TfidfVectorizer(stop_words='english')

In [24]:
x_transformed = vect.transform(X)


In [25]:
tfidf_vector_df = pd.DataFrame(x_transformed.toarray())

In [26]:
X1= tfidf_vector_df

In [27]:
X1.head

<bound method NDFrame.head of       0     1     2     3     4     5     6     7     8     9     ...  9517  \
0      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
1      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
2      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
3      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
4      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
...    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   ...   
6035   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
6036   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
6037   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
6038   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
6039   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   

      9518  9519  952

In [13]:
from imblearn.combine import SMOTEENN, SMOTETomek
from imblearn.over_sampling import BorderlineSMOTE, SMOTE, ADASYN, SMOTENC, RandomOverSampler

In [41]:
sm = SMOTE(random_state=777)
X, Y = sm.fit_resample(X1, Y1)

In [35]:
asm = ADASYN(random_state=777)
X, Y = asm.fit_resample(X1, Y1)

In [36]:
bsm = BorderlineSMOTE()
X, Y = bsm.fit_resample(X1,Y1)

In [42]:
from sklearn.model_selection  import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, Y,test_size = 0.20, random_state=26)

In [17]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
from sklearn.naive_bayes import MultinomialNB
from sklearn.ensemble import RandomForestClassifier

In [43]:

classifier = LogisticRegression(solver='lbfgs', max_iter=1000)
classifier.fit(x_train,y_train)
predicted = classifier.predict(x_test)
print("Logistic Regression Accuracy:",metrics.accuracy_score(y_test, predicted))
print("Logistic Regression Precision:",metrics.precision_score(y_test, predicted,average='micro'))
print("Logistic Regression Recall:",metrics.recall_score(y_test, predicted,average='micro'))


KeyboardInterrupt



In [44]:
mnb = MultinomialNB()

# fit
naive_model = mnb.fit(x_train,y_train)

# predict class
y_pred_class = mnb.predict(x_test)

# printing the overall accuracy
from sklearn import metrics
metrics.accuracy_score(y_test, y_pred_class)

0.9573590096286108

In [45]:
rf=RandomForestClassifier()
rus_model=rf.fit(x_train,y_train)
y_rus_class=rf.predict(x_test)
metrics.accuracy_score(y_test,y_rus_class)

0.9838376891334251

In [61]:
#X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=40)

In [72]:
print(X)

0       Your opinion about me? 1. Over 2. Jada 3. Kusr...
1       What's up? Do you want me to come online? If y...
2                            So u workin overtime nigpun?
3       Also sir, i sent you an email about how to log...
4       Please Stay At Home. To encourage the notion o...
                              ...                        
6035    Dear Customer,We have not received the schedul...
6036    Dear Customer Your DEBIT(ATM) Card BLOCKED Due...
6037    HDFC Ltd has requested payment of Rs. 8218. Li...
6038    Recharge Airtel No.using HDFC Bank A/C.Add Pre...
6039    Attention MANJU, Important message from HDFC B...
Name: TEXT, Length: 6040, dtype: object


In [108]:
print(x_transformed)

  (0, 8139)	0.31136341612244967
  (0, 7946)	0.3199443360541775
  (0, 7703)	0.2810435191815764
  (0, 7697)	0.2847086442401441
  (0, 7145)	0.1744244316523542
  (0, 6570)	0.1961634086614996
  (0, 6220)	0.28876025202132666
  (0, 5529)	0.3310070659200576
  (0, 5332)	0.2776975221554465
  (0, 5039)	0.3199443360541775
  (0, 4799)	0.3199443360541775
  (0, 2345)	0.31136341612244967
  (1, 9118)	0.3938559864389176
  (1, 8315)	0.5074478874717002
  (1, 6193)	0.5519847706963359
  (1, 3834)	0.3626595473113289
  (1, 2566)	0.3887993944311018
  (2, 9345)	0.5134533002487869
  (2, 6296)	0.6067807299443635
  (2, 5993)	0.6067807299443635
  (3, 9190)	0.25391765970645
  (3, 8914)	0.3418470657852267
  (3, 8484)	0.23974911685074168
  (3, 7719)	0.2452355528528717
  (3, 7538)	0.22366433181995168
  :	:
  (6038, 5793)	0.41049887973628085
  (6038, 5706)	0.30230613437930276
  (6038, 5668)	0.20153742291953516
  (6038, 4287)	0.29614407091538447
  (6038, 3615)	0.13225980656248543
  (6038, 1745)	0.09450699105343835
  (603

In [91]:
#type(x_transformed)

scipy.sparse.csr.csr_matrix

In [104]:
#x_transformed=x_transformed.todense()

In [105]:
#print(x_transformed)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [119]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()

In [120]:
vectorizer.fit(X)

CountVectorizer()

In [124]:
x_vtransformed=vectorizer.transform(X)

In [125]:
print(x_vtransformed)

  (0, 1193)	1
  (0, 2400)	1
  (0, 4926)	1
  (0, 5167)	1
  (0, 5463)	1
  (0, 5663)	1
  (0, 5684)	1
  (0, 6207)	1
  (0, 6387)	1
  (0, 6462)	1
  (0, 6750)	1
  (0, 7328)	1
  (0, 7891)	1
  (0, 7897)	1
  (0, 8149)	1
  (0, 8343)	1
  (0, 9757)	1
  (1, 1557)	1
  (1, 2281)	1
  (1, 2622)	1
  (1, 3189)	1
  (1, 3928)	1
  (1, 4686)	1
  (1, 5684)	1
  (1, 6358)	1
  :	:
  (6038, 8808)	5
  (6038, 8997)	1
  (6038, 9162)	1
  (6039, 533)	1
  (6039, 1267)	1
  (6039, 1664)	1
  (6039, 1778)	1
  (6039, 1845)	1
  (6039, 2539)	1
  (6039, 3069)	1
  (6039, 3875)	1
  (6039, 3971)	1
  (6039, 4392)	1
  (6039, 4398)	1
  (6039, 4455)	1
  (6039, 4721)	1
  (6039, 4733)	1
  (6039, 4757)	1
  (6039, 4825)	1
  (6039, 5607)	1
  (6039, 5670)	1
  (6039, 5742)	1
  (6039, 6165)	1
  (6039, 9662)	1
  (6039, 9757)	1


In [134]:
type(x_vtransformed)

scipy.sparse.csr.csr_matrix

In [137]:
x_transformed=x_vtransformed.toarray()

In [127]:
type(x_transformed)

numpy.ndarray

In [138]:
print(x_transformed)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [139]:
x_final = pd.DataFrame(x_transformed)

In [140]:
x_res, y_res = smote.fit_resample(x_final,Y)

In [141]:
type(x_res)

pandas.core.frame.DataFrame

In [142]:
print(sorted(Counter(y_res).items()))

[(0, 4846), (1, 4846), (2, 4846)]


In [143]:
print(x_res)

       0     1     2     3     4     5     6     7     8     9     ...  9787  \
0         0     0     0     0     0     0     0     0     0     0  ...     0   
1         0     0     0     0     0     0     0     0     0     0  ...     0   
2         0     0     0     0     0     0     0     0     0     0  ...     0   
3         0     0     0     0     0     0     0     0     0     0  ...     0   
4         0     0     0     0     0     0     0     0     0     0  ...     0   
...     ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   ...   
14533     0     0     0     0     0     0     0     0     0     0  ...     0   
14534     0     0     0     0     0     0     0     0     0     0  ...     0   
14535     0     0     0     0     0     0     0     0     0     0  ...     0   
14536     0     0     0     0     0     0     0     0     0     0  ...     0   
14537     0     0     0     0     0     0     0     0     0     0  ...     0   

       9788  9789  9790  9791  9792  97

In [144]:
#df1=pd.DataFrame(x_res,columns=['TEXT'])

In [145]:
#print(df1.head())

   TEXT
0   NaN
1   NaN
2   NaN
3   NaN
4   NaN


In [146]:
type(y_res)

pandas.core.series.Series

In [149]:
result=pd.concat([x_res,y_res],axis=1,join="inner")

In [150]:
print(result)

       0  1  2  3  4  5  6  7  8  9  ...  9788  9789  9790  9791  9792  9793  \
0      0  0  0  0  0  0  0  0  0  0  ...     0     0     0     0     0     0   
1      0  0  0  0  0  0  0  0  0  0  ...     0     0     0     0     0     0   
2      0  0  0  0  0  0  0  0  0  0  ...     0     0     0     0     0     0   
3      0  0  0  0  0  0  0  0  0  0  ...     0     0     0     0     0     0   
4      0  0  0  0  0  0  0  0  0  0  ...     0     0     0     0     0     0   
...   .. .. .. .. .. .. .. .. .. ..  ...   ...   ...   ...   ...   ...   ...   
14533  0  0  0  0  0  0  0  0  0  0  ...     0     0     0     0     0     0   
14534  0  0  0  0  0  0  0  0  0  0  ...     0     0     0     0     0     0   
14535  0  0  0  0  0  0  0  0  0  0  ...     0     0     0     0     0     0   
14536  0  0  0  0  0  0  0  0  0  0  ...     0     0     0     0     0     0   
14537  0  0  0  0  0  0  0  0  0  0  ...     0     0     0     0     0     0   

       9794  9795  9796  LABEL  
0     

In [151]:
X1=result.TEXT
Y1=result.LABEL



AttributeError: 'DataFrame' object has no attribute 'TEXT'

In [86]:
x_train1, x_test1, y_train1, y_test1 = train_test_split(X1, Y1,test_size = 0.20, random_state=26)


In [92]:
type(x_train1)

pandas.core.series.Series

In [87]:
mnb = MultinomialNB()

# fit
naive_model1 = mnb.fit(x_train1,y_train1)

# predict class
y_pred_class1 = mnb.predict(x_test1)

# printing the overall accuracy

metrics.accuracy_score(y_test1, y_pred_class1)

ValueError: setting an array element with a sequence.